### ISSUE TITLE
Running under Eclipse, can't detect messages from `chat1.html` if using Eclipse Navigator

### ISSUE THREAD

**Issue by jpaulm** [jpaulm/javafbp-websockets#4]
Running under Eclipse, MyWebSocketServer in WebSocketReceive can't detect messages from `chat1.html` if using Eclipse Navigator, but it works fine if I double-click on the `chat1.html` via Windows Explorer.  

It's probably a dumb bug, but the strange thing is that it used to work, but stopped working when I tried rebuilding the project.  It doesn't crash, it just ignores my messages!

I tried doing a `refresh` on Navigator, but it didn't seem to help!

@marci4 - does this suggest anything to you?!  Merci d'avance!

Paul

**Comment by jpaulm** [comment]
I tried just editing the `chat1.html` file via Navigator - and it worked!  Shouldn't refresh have done this?

**Comment by marci4** [comment]
Hello @jpaulm 

It could be that the Eclipse Navigator just does not support websockets. I don't have any eclipse here right now so I cannot check this!

Greetings
marci4

**Comment by jpaulm** [comment]
Hi @marci4 , once I made a trivial edit to the `chat1.html` file, everything worked - even using Navigator to access it.  Just doing Refresh didn't make a difference, though - could be some kind of Navigator problem.  One of life's mysteries!  Thanks anyway!

Paul

**Comment by jpaulm** [comment]
I have updated the Readme to describe this behaviour - the consensus seems to be that I can't do anything about this, so I will close this issue.  Thanks, everyone!

**Comment by jpaulm** [comment]
I have just published v1.2.3 of JavaFBP-WebSockets.  After starting com.jpaulmorrison.fbp.examples.networks.TestWebSockets, I click on chat1, and select OpenWith - and select Web Browser.  

This does not seem to work _within_ Eclipse; however, if I select Web Browser under the Win10 File Explorer, it works fine! I have updated Readme accordingly.
